### ISSUE TITLE
Build error MacOS - boost

### ISSUE THREAD

**Issue by hubtub** [wavii/pfp#14]
I am trying to build on MacOs 10.10

I installed boost using homebrew.
Using make I get the following error:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DNDEBUG -Dpfp_EXPORTS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fPIC -I/Users/stefan/Code/Brain/pfp/include -I/usr/include/python2.6    -Wall -O3 -o CMakeFiles/pfp.dir/src/pfp/tokenizer.yy.o -c /Users/stefan/Code/Brain/pfp/src/pfp/tokenizer.yy.cpp
In file included from ../etc/tokenizer.flex:5:
/Users/stefan/Code/Brain/pfp/include/pfp/tokenizer.h:7:10: fatal error: 'boost/optional.hpp' file not found
# include <boost/optional.hpp>

```
     ^
```

1 error generated.

I am not sure, why boost/optional.hpp is not part of the homebrew packet.
What is needed form this packet?

Is there a binary MacOS distribution somewhere with python bindings?
